### ISSUE TITLE
Confusion regarding installation. 

### ISSUE THREAD

**Issue by darshanime** [mblondel/lightning#31]
I have the option to install via `pip` :
`pip install https://github.com/mblondel/lightning/archive/master.zip`

Or from source:
```
git clone https://github.com/mblondel/lightning.git
cd lightning
python setup.py build
sudo python setup.py install
```

What I wanted to know was; 
1. What is the difference ?
2. I plan to fork this repo and contribute to it, in that case, should I install from source ?
3. How do I view the effects of the changes I make to my local code clone ?

**Comment by mblondel** [comment]
Hi!

> 1. What is the difference ?

Pip installs the project directly in your Python distribution. The second makes a local copy and installs it to your Python distribution.

> 2. I plan to fork this repo and contribute to it, in that case, should I install from source ?

Yes. It's better to edit the local copy than the files in your Python distribution.

> 3. How do I view the effects of the changes I make to my local code clone ?

One solution is to run `sudo python setup.py install` every time but this is not very convenient.

Personally, I have added lightning to the PYTHONPATH environment variable in my .bashrc file:

```
export PYTHONPATH=/path/to/lightning:$PYTHONPATH
```
where `/path/to/lightning` is the project root folder (the one containing the README.rst file). This way, Python will look in this folder when doing `import lightning`.

lightning contains a few C files that must be compiled directly in the project. This can be done with 
```
make inplace
```
at the project root. Let me know if something was unclear.

**Comment by darshanime** [comment]
Neat!

I was also wondering about virtual envs (Anaconda). Can they be used ?

Also, if instead of changing my PYTHONPATH environment variable, if I `cd` into the root folder before importing lightning, won't it have the same effect ?

**Comment by mblondel** [comment]
> I was also wondering about virtual envs (Anaconda). Can they be used ?

Not sure what you mean.

> Also, if instead of changing my PYTHONPATH environment variable, if I cd into the root folder before importing lightning, won't it have the same effect ?

This will only work if you put your .py files at the project root, which I don't recommend.

**Comment by darshanime** [comment]
So, basically I should install via source, point my PYTHONPATH to the project dir and compile each time I make a change.

**Comment by mblondel** [comment]
Exactly.

**Comment by darshanime** [comment]
Thank you, I am sorted.
