### ISSUE TITLE
Implementation of SAGA

### ISSUE THREAD

**Issue by fabianp** [mblondel/lightning#34]
Hi @mblondel :-)

I'm working on an implementation of [SAGA](http://arxiv.org/pdf/1407.0202.pdf) for a project of mine. My question is: if I submit such implementation (based on the SAG implementation already in lightning), would be considered for inclusion ?.

Best,

Fabian

**Comment by mblondel** [comment]
Hi Fabian. Yes, such a contribution would be more than welcome :)

BTW the SAG implementation seems to be incorrect in the sparse case, see #33.

**Comment by mblondel** [comment]
Now in master, closing.
